baseURL: https://www.mitsu9.com/
theme: pure
title: mitsu9.com
defaultContentLanguage: en  # en/zh/...
footnoteReturnLinkContents: ↩
hasCJKLanguage: true
paginate: 7
enableEmoji: true
pygmentsCodeFences: false
googleAnalytics: "UA-156048792-1" # UA-XXXXXXXX-X
permalinks:
  posts: /:year/:month/:filename/

taxonomies:
    category : categories
    tag : tags
    series : series
outputFormats:          # use for search. recommend not to modify
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
    home: ["HTML","RSS","SearchIndex"]  # recommend not to modify
# sitemap
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: home
      name: Home
      title: Home
      url: /
      weight: 1

    - identifier: archives
      name: Archives
      title: Archives
      url: /posts
      weight: 2

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags
      weight: 4

    - identifier: about
      name: About
      title: About
      url: /about
      weight: 5


params:
  since: 2019
  dateFormatToUse: "2006-01-02"
  enablePostCopyright: false
  # the directory under content folder that you want to render
  mainSections: ["posts"]
  # Enable/Disable menu icons
  # Icon Reference: http://blog.cofess.com/hexo-theme-pure/iconfont/demo_fontclass.html
  enableMathJax: true #Enable mathjax support, to use mathematical notations
  highlightjs:
    langs: ["python", "javascript"] # refer to http://staticfile.org/, search highlight.js, already have highlight.min.js
  customCSS: css/custom.css

  menuIcons:
    enable: true  # 是否启用导航菜单图标
    home: icon-home-fill
    archives: icon-archives-fill
    categories: icon-folder
    tags: icon-tags
    repository: icon-project
    books: icon-book-fill
    links: icon-friendship
    about: icon-cup-fill

  # profile
  profile:
    enabled: true # Whether to show profile bar
    avatar: img/profile.jpg
    author: Mitsunobu Homma
    author_title: Customer Reliability Engineer
    author_description: description
    location: Tokyo, Japan
    follow: https://twitter.com/_mitsu9
    # Social Links
    social:
      links:
        github: https://github.com/mitsu9
        twitter: https://twitter.com/_mitsu9
        facebook: https://www.facebook.com/mitsunobu.homma
        rss: /index.xml
      link_tooltip: true # enable the social link tooltip, options: true, false

  # Site
  site:
    logo:
      enabled: true
      width: 40
      height: 40
      url: favicon.ico
    favicon: favicon.ico

  # Share
  # weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
  share:
    enable: true # 是否启用分享
    sites: twitter # PC端显示的分享图标
    mobile_sites: twitter # 移动端显示的分享图标

  # config
  config:
    skin: theme-green # theme color default is white. other type [theme-black,theme-blue,theme-green,theme-purple]
    layout: main-center # main-left main-center main-right
    excerpt_link: Read More
    toc: false

  comment:
    enable: false

  # Sidebar
  sidebar: right

  # Search
  search:
    enable: true # enable search. thanks for https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/master/source/js/insight.js

  # Sidebar only the following widgets. you can remove any you don't like it.
  widgets:
    - category
    - tag
    - recent_posts
