name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Git Submodules Init
      run: git submodule update --init --recursive
    - name: Hugo Action
      uses: srt32/hugo-action@v0.0.3
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        version: '3.7'
        architecture: 'x64'
    - name: Install awscli
      run: pip install --upgrade pip awscli
    - name: AWS S3 Sync Action
      run: aws s3 sync --exact-timestamps ./public s3://${{ secrets.AWS_S3_BUCKET }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
